### ISSUE TITLE
Does not check arguments length before calling apply

### ISSUE THREAD

**Issue by oculus42** [alexeisavca/polymorph.js#3]
If the function is called with an unsupported number of elements, you get one of two possible errors.

Demo code
```javascript
var test = polymorph(
    function(a){ console.log('One'); },
    function(a,b){console.log('Two'); }
);
```

With no arguments `test()` returns `Uncaught TypeError: Cannot read property 'length' of undefined`
With extra arguments, `test()` returns `Uncaught TypeError: Cannot read property 'apply' of undefined`

The code should check for a valid number of arguments and throw an appropriate error. Perhaps `SyntaxError: Unexpected argument count`?

**Comment by alexeisavca** [comment]
Ok. Are you working on this('cause I saw you forked) or should I look into this issue?

**Comment by oculus42** [comment]
I added a pull request and incremented the version, but didn't update the changelog with the details.
